-- MySQL Script generated by MySQL Workbench
-- Sun Apr 14 11:08:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectDataBase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectDataBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectDataBase` ;
USE `projectDataBase` ;

-- -----------------------------------------------------
-- Table `projectDataBase`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDataBase`.`Role` (
  `idRole` INT NOT NULL,
  `NameRole` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectDataBase`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDataBase`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `Role` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `SecondName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE,
  INDEX `fk_Users_Role_idx` (`Role` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Role`
    FOREIGN KEY (`Role`)
    REFERENCES `projectDataBase`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectDataBase`.`Priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDataBase`.`Priority` (
  `idPriority` INT NOT NULL,
  `NamePriority` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idPriority`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectDataBase`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDataBase`.`Project` (
  `idProject` INT NOT NULL,
  `Summary` VARCHAR(45) NULL,
  `NameProject` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProject`),
  UNIQUE INDEX `NameProject_UNIQUE` (`NameProject` ASC) VISIBLE,
  UNIQUE INDEX `idProject_UNIQUE` (`idProject` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectDataBase`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDataBase`.`Status` (
  `idStatus` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatus`),
  UNIQUE INDEX `idStatus_UNIQUE` (`idStatus` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectDataBase`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDataBase`.`Task` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(200) NOT NULL,
  `DueData` DATE NOT NULL,
  `Estimation` DATE NOT NULL,
  `Assigne` VARCHAR(45) NOT NULL,
  `TicketCode` VARCHAR(40) NOT NULL,
  `CreateDate` DATE NOT NULL,
  `UpdateDate` DATE NOT NULL,
  `Reporter` INT NOT NULL,
  `Priority` INT NOT NULL,
  `Project` INT NOT NULL,
  `Comments` VARCHAR(45) NULL,
  `Attachment` VARCHAR(45) NULL,
  `Status` INT NOT NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_Users1_idx` (`Reporter` ASC) VISIBLE,
  INDEX `fk_Task_Priority1_idx` (`Priority` ASC) VISIBLE,
  INDEX `fk_Task_Project1_idx` (`Project` ASC) VISIBLE,
  UNIQUE INDEX `TicketCode_UNIQUE` (`TicketCode` ASC) VISIBLE,
  INDEX `fk_Task_Status1_idx` (`Status` ASC) VISIBLE,
  CONSTRAINT `fk_Task_Users1`
    FOREIGN KEY (`Reporter`)
    REFERENCES `projectDataBase`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Priority1`
    FOREIGN KEY (`Priority`)
    REFERENCES `projectDataBase`.`Priority` (`idPriority`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Project1`
    FOREIGN KEY (`Project`)
    REFERENCES `projectDataBase`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Status1`
    FOREIGN KEY (`Status`)
    REFERENCES `projectDataBase`.`Status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectDataBase`.`sign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDataBase`.`sign` (
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  INDEX `fk_sign_Users1_idx` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `Users_idUsers_UNIQUE` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_sign_Users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `projectDataBase`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
